services:
  server:
    build: "./server"
    environment:
      RUST_LOG: debug
      DATABASE_URL: postgresql://sfls:sfls@database:5432/sfls
    ports:
      - "10000:8080"
    depends_on:
      - database

  gateway:
    build: "./gateway"
    environment:
      BASE_URL: http://server:8080
    ports:
      - "10001:3000"
    depends_on:
      - server

  database:
    image: pgedge/pgedge:pg16-latest
    ports:
      - "5432:5432"
    volumes:
      - "./db.json:/home/pgedge/db.json"
