[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }

anyhow = { workspace = true }
async-trait = { workspace = true }
diesel-async = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
